name: Upload zipped Artifact
description: Matches actions/upload-artifact, except it compress files with zip prior to uploading to improve the speed of upload

inputs:
  name:
    description: Name of the artifact file
    required: false
  path:
    description: A file, directory or wildcard pattern that describes what to upload.
    required: true
  exclusions:
    description: |
      Globs to exclude, refer to `thedoctor0/zip-release` for usage
      https://github.com/TheDoctor0/zip-release
    required: true
  if-no-files-found:
    required: false
  retention-days:
    required: false

runs:
  using: 'composite'
  steps:
    - uses: thedoctor0/zip-release@4fb9e4f # Review updates manually
      with:
        filename: artifact.zip
        path: dist
        exclusions: ${{ inputs.exclusions }}

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.name }}
        path: artifact.zip
        if-no-files-found: ${{ inputs.if-no-files-found }}
        retention-days: ${{ inputs.retention-days }}

    - run: rm artifact.zip
      shell: 'bash'
