name: Release

env:
  DIRECTORY: distribution
  PROJECT_NAME: extension

on:
  push:
  workflow_dispatch:
  # You can manually trigger a deployment on GitHub.com
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  schedule:
    - cron: '59 * * * *'

jobs:
  ternary:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(env.AND) }}'
        env:
          AND: ${{ secrets.MISSING == '1' && 'hello'  }}
      - run: echo '${{ toJSON(env.OR) }}'
        env:
          OR: ${{ secrets.MISSING == '1' || 'hello' }}
  Version:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config user.email $GITHUB_ACTOR@users.noreply.github.com
      - run: gh release create 2
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
