name: Deployment
on:
  push:
    branches: 
      - master
    tags:
      - '*'
  schedule:
    - cron: '*/5 * 1 1 1'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git tag -l --points-at HEAD
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - run: node -e "console.log(process.env.GITHUB_REF);console.log(process.env.GITHUB_REF.replace('/refs/tags/', ''))"
