name: Deployment
on:
  push:
    branches: 
      - master
    tags:
      - '*'
  schedule:
    - cron: '*/5 * 1 1 1'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git tag -l --points-at HEAD
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - run: node -e "const util = require('util'); util.promisify(require('child_process').execFile)('git', ['tag', '-l']).then(function (a) {console.log(JSON.stringify(a), typeof a, a.stdout, 'lol')}).catch(console.error)"
