name: Deployment
on:
  push:
    branches: 
      - master
    tags:
      - '*'
  schedule:
    - cron: '*/5 * 1 1 1'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir distribution && echo test > distribution/yoooooo.txt
    - uses: actions/upload-artifact@v2
      with:
        path: distribution
        
  deploy-to-chrome:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
    - run: ls -a
    - run: cat artifact/yoooooo.txt
