name: Loom Reminder

on:
  pull_request_review:
    types:
      - submitted

jobs:
  reminder:
  #  if: github.event.review.state == 'approved'

    runs-on: ubuntu-latest

    steps:
      - name: Find first loom
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PR=${{ github.event.pull_request.number }}
          printenv
      - run: printenv
      - name: Post loom if present
        uses: marocchino/sticky-pull-request-comment@v2
        if: env.PR
        with:
          message: |
            After the PR is merged, this loom will be posted to #sprint-demo on Slack:
            
            ${{ env.PR }}
