name: Loom Reminder

on:
  pull_request_review:
    types:
      - submitted

jobs:
  reminder:
  #  if: github.event.review.state == 'approved'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Find first loom
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr view ${{ github.event.pull_request.number }} |
          grep "https://www.loom.com/share/\w\{32\}" --max-count 1 --only-matching |
          tee LOOM_LINK || true

          # Also store it in a $LOOM_LINK global env
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
          echo "LOOM_LINK=$(cat LOOM_LINK)" >> $GITHUB_ENV

      - run: printenv
      - name: Post loom if present
        uses: marocchino/sticky-pull-request-comment@v2
        if: env.LOOM_LINK
        with:
          message: |
            After the PR is merged, this loom will be posted to #sprint-demo on Slack:
            
            ${{ env.LOOM_LINK }}
