name: CI

on: [push]

jobs:
  create-version:
    runs-on: ubuntu-latest
    steps:
    - run: echo lol
    - run: exit
    - run: echo 4
  build:
    runs-on: ubuntu-latest
    needs: [create-version]
    steps:
    - uses: actions/checkout@v2
    - name: Save cash
      run: |
        echo 2
