name: CI

on: [push]

jobs:
  create-version:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - run: echo lol
    - run: echo "${{ toJson(github) }}"
    - run: echo "::set-output name=action_fruit::strawberry"
  build:
    runs-on: ubuntu-latest
    needs: [create-version]
    if: 'true'
    steps:
    - uses: actions/checkout@v2
    - name: Save cash
      run: |
        echo 2
