name: CI

on: [push]

jobs:

  yo:
    runs-on: ubuntu-latest
    steps:
    - run: echo lol
    - run: echo "${{ toJson(github) }}"
    - name: cancelling
      uses: andymckay/cancel-action@0.2
    - run: sleep 100
     
  version:
    runs-on: ubuntu-latest
    needs: yo
    steps:
    - run: echo lol
    - run: echo "${{ toJson(github) }}"
  build:
    runs-on: ubuntu-latest
    needs: version
    steps:
    - uses: actions/checkout@v2
    - name: Save cash
      run: |
        echo 2
