name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install primereact
      - run: npm install @types/react
      - run: npm install typescript
      - run: echo 'import { TreeTable } from "primereact/treetable";' > index.ts
      - run: |
          echo '{"compilerOptions": {"skipLibCheck": false, "lib": ["ES2019","ES2020.String","DOM"]}}' > tsconfig.json
      - run: npx tsc index.ts --p tsconfig.json
