name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOURCE_MAP_PATH: sourcemaps/${{ github.job }}/${{ github.sha }}
      SOURCE_MAP_URL_BASE: https://pixiebrix-extension-source-maps.s3.amazonaws.com/${{ env.SOURCE_MAP_PATH }}
    steps:
      - run: echo $SOURCE_MAP_PATH
      - run: echo $SOURCE_MAP_URL_BASE
