name: Deployment

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: git tag -l --points-at HEAD
    - uses: git fetch --tags
    - uses: git tag -l --points-at HEAD
