name: Deployment

on: [push]

jobs:

  create-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: head
        run: echo "::set-output name=was-tagged::"$(git tag)
      - run: echo ${{ steps.head.outputs.was-tagged }}
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: ! steps.head.outputs.was-tagged
        run: |
          export VER=$(npx daily-version)
          git tag $VER -m $VER
          git push origin $VER

  build:
    needs: create-version
    if: github.event_name == 'pushNO' || needs.create-version.outputs.created
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm test
    - name: Update extension’s meta
      run: |
        export VER=$(echo "$GITHUB_REF" | sed -e 's/refs\/tags\///')
        echo https://github.com/$GITHUB_REPOSITORY/tree/$VER > distribution/SOURCE_URL
        npm run version
    - uses: actions/upload-artifact@v1
      with:
        name: built-extension
        path: distribution

  deploy-to-chrome:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: built-extension
        path: distribution
    - run: cd distribution && npx chrome-webstore-upload-cli upload --auto-publish
      env:
        EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

  deploy-to-firefox:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: built-extension
        path: distribution
    - run: cd distribution && npx web-ext-submit
      env:
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
