name: Loom to slack

on:
  workflow_call: # Enable workflow reuse/import
  pull_request_review:
    types:
      - submitted
  pull_request:
    types:
      - closed

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(github)}}
