name: Loom to slack

on:
  push:

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR status
        run: |
          STATUS=$(
            gh pr view 6082 --json state --jq .state --repo refined-github/refined-github
          )
          echo STATUS=$STATUS >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo $STATUS
      - run:
      - run: echo ${{ env.WEWE}}
