name: dependabot

on:
   pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  lockfile-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: echo lol > newfile
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update lockfile
