name: dependabot

on:
   pull_request_target:
     branches:
       - "dependabot/submodules/**"

permissions:
  pull-requests: write
  contents: write

jobs:
  lockfile-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: npm
      - run: npm install
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update lockfile
