name: PR
on: pull_request
jobs:
  strictNullChecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get list of changed files
        id: changedfiles
        uses: tj-actions/changed-files@v42
        with:
          json: "true"
          files: "src/**/*.{ts,tsx}"
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
      - name: Verify that new files in this PR appear in tsconfig.strictNullChecks.json
        uses: actions/github-script@v7
        with:
          script: |
            const tsconfigJson = require('./tsconfig.strictNullChecks.json');
            const newFiles = JSON.parse('${{ steps.changedfiles.outputs.added_files }}')
            if (newFiles.length === 0) {
              console.log('No new files found');
              return;
            }

            for (const newFile of newFiles) {
              if (tsconfigJson.files.includes(newFile.replace('src', '.'))) {
                console.log(`${newFile} is in tsconfig.strictNullChecks.json`);
                continue;
              }

              core.error(`${newFile} was not found in tsconfig.strictNullChecks.json`, {
                title: 'strictNullChecks',
                file: newFile,
              });
              process.exitCode = 1;
            }
