name: PR
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: package-lock.json
      - id: stats
        run: |
          git remote
          git fetch origin ${{ github.base_ref }}
          STAT="$(git diff --numstat origin/${{ github.base_ref }}..HEAD -- package-lock.json)"

          DELETED="$(echo $STAT | cut -f1)"
          ADDED="$(echo $STAT | cut -f2)"
          TOTAL_CHANGES=$((DELETED + ADDED))
          echo "STAT=$STAT"
          echo "Total changes in package-lock.json: $TOTAL_CHANGES"
          echo "changes=$TOTAL_CHANGES" >> $GITHUB_OUTPUT
      - name: leave annotation comment on pr
        if: steps.stats.outputs.changes > 10
        run: |
          echo "::error file=package-lock.json::package-lock.json has more than 1000 lines changed. Please check if this is intended."
