name: PR
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get list of changed files
        id: changesAction
        uses: tj-actions/changed-files@v42
        with:
          json: "true"
          files: |
            **.ts
            **.tsx
      - name: Verify that new files in this PR appear in tsconfig.strictNullChecks.json
        uses: actions/github-script@v7
        with:
          script: |
            const tsconfigJson = require('./tsconfig.strictNullChecks.json');
            const newFiles = ${{ steps.changesAction.outputs.added }};
            console.log('New files:', newFiles)
            const newFilesNotInTsconfig = newFiles.filter(file => !tsconfigJson.include.includes(file));
            if (newFilesNotInTsconfig.length > 0) {
              throw new Error(`The following new files are not included in tsconfig.strictNullChecks.json: ${newFilesNotInTsconfig.join(', ')}`);
            }
