name: Loom to slack

on:
  workflow_call: # Enable workflow reuse/import
  pull_request:
    types:
      - closed

jobs:
  post:
    if: github.event.pull_request.merged

    runs-on: ubuntu-latest

    steps:
      - run: echo 1
