on: [push]

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - run:  echo "PUBLIC_RELEASE=" >> $GITHUB_ENV
    - run:  echo my name is $ac
      env:
        ac: ${{ env.DAY_OF_WEEK == 'Mon' }}
