on: push


jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      a: 'true'
      b: ${{ github.ref == 'refs/heads/master' }}
      c: ${{ github.ref == 'refs/heads/c' }}
    steps:
    - run: echo $a
      if: ${{ toJSON(env.a) }}
    - run: echo $b
      if: ${{ toJSON(env.b) }}
    - run: echo $c
      if: ${{ toJSON(env.c) }}
