on: push

env:
  abc: ABC
  cde: CDE
  fgh: FGH
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - run: echo $a - $b - $c
      env: 
        a: $abc
        b: ${{ env.cde }}
        c: env.fgh
    - run: echo releasing
      if: env.PUBLIC_RELEASE == true
