on: [push]

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - run:  echo "PUBLIC_RELEASE=" >> $GITHUB_ENV
    - run:  echo my name is $ac
      env:
        ac: ${{ github.ref == 'refs/heads/master' || contains(github.ref, 'release/') }}
