on: push

env:
  abc: ABC
  cde: CDE
  fgh: FGH
jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      # Uploads sourcemaps to S3, if it's a public release
      SOURCE_MAP_PATH: sourcemaps/${{ github.job }}/${{ github.sha }}
    steps:
    - run: echo $SOURCE_MAP_PATH
