on: push


env:
  # Creates and uploads sourcemaps to Rollbar, and save the built extension as an artifact
  PUBLIC_RELEASE: ${{ github.ref == 'refs/heads/main' || true }}
  # Creates and uploads sourcemaps to Rollbar, and save the built extension as an artifact
  PUBLIC_RELEASEA: ${{ github.ref == 'refs/heads/master' }}
jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      # Uploads sourcemaps to S3, if it's a public release
      SOURCE_MAP_PATH: sourcemaps/$PUBLIC_RELEASE
    steps:
    - run: echo $SOURCE_MAP_PATH - $PUBLIC_RELEASE - $PUBLIC_RELEASEA
