on: [push]

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      PUBLIC_RELEASE: ${{ github.ref == 'refs/heads/main' || contains(github.ref, 'release/') }}
    steps:
    - run: echo $PUBLIC_RELEASE
    - run: echo releasing
      if: env.PUBLIC_RELEASE == true
