on: push


jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      # Creates and uploads sourcemaps to Rollbar, and save the built extension as an artifact
      PUBLIC_RELEASE: 'true'
      # Creates and uploads sourcemaps to Rollbar, and save the built extension as an artifact
      PUBLIC_RELEASEA: ${{ github.ref == 'refs/heads/sdas' }}
    steps:
    - run: echo $PUBLIC_RELEASE
      if: ${{ env.PUBLIC_RELEASE == 'true' }} # boolean comparison required
    - run: echo $PUBLIC_RELEASEA
      if: ${{env.PUBLIC_RELEASEA == 'true' }} # boolean comparison required
    - run: echo $PUBLIC_RELEASE
      if: ${{env.PUBLIC_RELEASE }}
    - run: echo $PUBLIC_RELEASEA
      if: ${{env.PUBLIC_RELEASEA }}
