name: Loom Reminder

on:
  pull_request_review:
    types:
      - submitted
      - edited

jobs:
  call-workflow-passing-data:
    uses: fregante/sandbox/.github/workflows/r.yml@master
    secrets: inherit
