name: Loom Reminder

on:
  pull_request_review:
    types:
      - submitted

jobs:
  call-workflow-passing-data:
    uses: pixiebrix/pixiebrix-extension/.github/workflows/loom-reminder.yml@F/dx/loom-to-slack
    secrets: inherit
