# Collaborators can publish a new version **of what's on master** by leaving a review on any PR, generally the PR that just closed.
# To trigger this, the comment must match the format `🚀 version`, where "version" is anything accepted by `npm version XXX`

name: Publish

on:
  commit_comment:
    types:
      - created

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $COMMENT
        env:
          COMMENT: ${{ toJson(github.event) }}
  npm:
    runs-on: ubuntu-latest
    if: contains('OWNER,COLLABORATOR', github.event.comment.author_association) && startsWith(github.event.comment.body, '🚀')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: npm install
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: npm version
        run: |
          WORDS=($COMMENT)
          echonpm version ${WORDS[1]}
        env:
          COMMENT: ${{ github.event.review.body }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: git push --follow-tags
