name: Yo

on:
  pull_request_review:
    types:
      - submitted

jobs:

  Publish:
    runs-on: ubuntu-latest
    if: github.event.review.author_association == 'OWNER'
    steps:
      - name: is owner
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.review) }}
        run: echo "$GITHUB_CONTEXT"

  arraycontainscollab:
    runs-on: ubuntu-latest
    if: contains(['OWNER', 'COLLABORATOR'], github.event.review.author_association)
    steps:
      - name: is owner
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.review) }}
        run: echo "$GITHUB_CONTEXT"

  B:
    runs-on: ubuntu-latest
    if: startsWith(github.event.review.body, '🚀')
    steps:
      - name: deploy review
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.review) }}
        run: echo "$GITHUB_CONTEXT"
