name: Yo

on:
  push:
    branches: 
      - master

jobs:

  Publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - cd artifact && npx chrome-webstore-upload-cli@1 upload --auto-publish
          - cd artifact && npx web-ext-submit@4
    steps:
    - uses: actions/download-artifact@v2
    - run: ${{ matrix.command }}
      env:
        # Chrome
        EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        # Firefox
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
