name: Publish

on:
  pull_request_review:
    types:
      - submitted

jobs:

  npm:
    runs-on: ubuntu-latest
    if: contains('OWNER,COLLABORATOR', github.event.review.author_association) && startsWith(github.event.review.body, '🚀')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: npm install
      - run: |
          WORDS=($COMMENT)
          echo npm version ${WORDS[1]}
        env:
          COMMENT: ${{ toJson(github.event.review.body) }}
